apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    acornsoft.io/workload-group-no: "1"
  generation: 1
  labels:
    app: commerce-product
  name: commerce-product-v2
  namespace: bb-edu
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: commerce-product
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: commerce-product
        version: v2
    spec:
      containers:
      - image: 192.168.100.12/bb-edu/commerce-product:
        imagePullPolicy: Always
        name: product-container
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: commerce-cocktail-t8ceb0dry5v7
